# Generated by Django 6.1 on 2026-08-27 08:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('nationalite', models.CharField(blank=True, max_length=100)),
                ('date_naissance', models.DateField(blank=True, help_text="Sert à vérifier qu'un film ne sort pas avant la naissance du réalisateur.", null=True)),
            ],
            options={
                'verbose_name': 'réalisateur',
                'verbose_name_plural': 'réalisateurs',
                'ordering': ['nom', 'prenom'],
                'constraints': [models.UniqueConstraint(fields=('nom', 'prenom'), name='realisateur_unique_nom_prenom')],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('annee_sortie', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1895), django.core.validators.MaxValueValidator(2100)], verbose_name='année de sortie')),
                ('duree_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)], verbose_name='durée (minutes)')),
                ('genre', models.CharField(choices=[('ACTION', 'Action'), ('COMEDIE', 'Comédie'), ('DRAME', 'Drame'), ('SF', 'Science-fiction'), ('HORREUR', 'Horreur'), ('ANIMATION', 'Animation'), ('DOCU', 'Documentaire')], default='DRAME', max_length=20)),
                ('synopsis', models.TextField(blank=True)),
                ('note', models.DecimalField(blank=True, decimal_places=1, help_text='Note sur 10, avec une décimale (ex: 8.5). Peut rester vide.', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('realisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='films.realisateur', verbose_name='réalisateur')),
            ],
            options={
                'ordering': ['-annee_sortie', 'titre'],
                'constraints': [models.UniqueConstraint(fields=('titre', 'realisateur'), name='film_unique_titre_par_realisateur')],
            },
        ),
    ]
